twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        # point this wherever your images live
        '%kernel.project_dir%/public/images': img
    form_themes: ['bootstrap_5_layout.html.twig']
    
when@test:
    twig:
        strict_variables: true
